### ISSUE TITLE
希望能增加无公网机器监控

### ISSUE THREAD

**Issue by jkfujr** [souying/serverMmon#12]
rt，面板在一个vps上，希望能监控无公网的家宽设备

**Comment by souying** [comment]
> rt，面板在一个vps上，希望能监控无公网的家宽设备

只能在区域网中  最多定时推送监控信息到tg

**Comment by jkfujr** [comment]
有更新计划么，参考隔壁哪吒监控的方式（

**Comment by souying** [comment]
> 有更新计划么，参考隔壁哪吒监控的方式（

我大概懂了 内网机子有网 定时推送到面板

**Comment by jkfujr** [comment]
是的√

**Comment by jkfujr** [comment]
指的是无公网ip，互联网还是有的
