### ISSUE TITLE
自动安装vnstat失败，然后按照INSTALL处理，结果一直无法显示

### ISSUE THREAD

**Issue by wolfdan666** [souying/serverMmon#15]
一开始脚本安装vnstat失败
```bash
cp -fv vnstat.conf.new /etc/vnstat.conf
'vnstat.conf.new' -> '/etc/vnstat.conf'

============================================================================
  Note: No service file has been installed for starting the daemon
        automatically. Such setup will need to be created manually
        depending on the used environment. See the included documentation.
============================================================================

make[3]: Leaving directory '/tmp/vnstat-2.10'
make[2]: Leaving directory '/tmp/vnstat-2.10'
make[1]: Leaving directory '/tmp/vnstat-2.10'
Failed to enable unit: Unit file vnstat.service does not exist.
Unit vnstat.service does not exist, proceeding anyway.
Failed to restart vnstat.service: Unit vnstat.service not found.

vnStat流量监控 服务启动出错，请手动处理！
> 重启Mmon
```

然后我按照编译报错提示，以及vnstat下面INSTALL做了如下操作:
```bash
cp -v examples/init.d/debian/vnstat /etc/init.d/
vnstat defaults
service vnstat star'examples/init.d/debian/vnstat' -> '/etc/init.d/vnstat'
```

之后Mmon日志获取显示如下，但是网页端一直显示 **维修中**

> 获取Mmon日志
-- Logs begin at Tue 2022-11-15 16:55:37 CST. --
Jun 27 13:07:43 amd2u mmon[13471]: V8内核8.4.371.23-node.87
Jun 27 13:07:44 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:07:45 amd2u mmon[13471]: MMON主机信息修正成功
Jun 27 13:07:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:08:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:09:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:10:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:11:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:12:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:13:59 amd2u mmon[13471]: vnstat数据采集成功
Jun 27 13:14:59 amd2u mmon[13471]: vnstat数据采集成功

两个服务器都报错 vnstat 安装失败，都是 ubuntu18.04， 但是之前安装成功的服务器也是 ubuntu18.04

**Comment by souying** [comment]
> 
请开端口 防火墙  试一试  浏览器访问自己的 监控端服务器ip加端口

**Comment by wolfdan666** [comment]
尴尬，是有人给我的服务器装了防火墙，之前我自己一直以为是没开防火墙的，谢谢大佬
