### ISSUE TITLE
 客户机占用资源有点高 

### ISSUE THREAD

**Issue by niu12503** [souying/serverMmon#6]
客户机占用资源有点高 
小破机感觉占用高了

**Comment by souying** [comment]
什么配置的 这边测试512 0.5h 的也没问题  再小的没测试guo

**Comment by niu12503** [comment]
甲骨文的AMD 1H1G的那种，cpu直接占用20-30%之间     [https://pic.840606.xyz/file/42a306e08d825b9963730.png](url)

**Comment by souying** [comment]
> 甲骨文的AMD 1H1G的那种，cpu始终 占用20-30%之间 ![image](https://user-images.githubusercontent.com/21340487/228997737-df8ad0c5-b3ba-42f7-aa37-266e778594ac.png)

![image](https://user-images.githubusercontent.com/20512945/229081938-40e22101-13ed-4374-b4ca-bba4e688e759.png)
已经优化  
执行   ps aux|head -1;ps aux|sort -rn -k3|head -10   具体看看占用了多少
